# Generated by Django 5.0.2 on 2024-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_username_customuser_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(max_length=4),
        ),
    ]
