# Generated by Django 5.0.2 on 2024-07-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
