# Generated by Django 5.0.2 on 2024-08-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sink_node_sk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink_node',
            name='SK_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
