# Generated by Django 5.0.2 on 2024-08-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sink_node_sk_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink_node',
            name='autoName_increment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
