# Generated by Django 5.0.2 on 2024-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sink_node_autoname_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sink_node',
            name='autoName_increment',
        ),
        migrations.AddField(
            model_name='sink_node',
            name='increment_id',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
