# Generated by Django 5.0.2 on 2024-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sensor_node_sensornode_name_sensor_node_increment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_node',
            name='increment_id',
            field=models.IntegerField(editable=False),
        ),
    ]
