# Generated by Django 5.0.2 on 2024-08-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_sensor_node_increment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor_Node',
            new_name='SensorNode',
        ),
        migrations.RenameModel(
            old_name='Sink_Node',
            new_name='SinkNode',
        ),
        migrations.RenameField(
            model_name='sensornode',
            old_name='Sink_Node',
            new_name='SinkNode',
        ),
    ]
