# Generated by Django 5.0.2 on 2024-08-16 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_sensor_node_sensornode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornode',
            name='SinkNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_nodes', to='api.sinknode'),
        ),
        migrations.CreateModel(
            name='SKReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('Sink_Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sinknode')),
            ],
        ),
        migrations.CreateModel(
            name='SNReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('soil_moisture', models.DecimalField(decimal_places=7, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Sensor_Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensornode')),
            ],
        ),
        migrations.DeleteModel(
            name='Readings',
        ),
    ]
