# Generated by Django 5.0.2 on 2024-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sensornode_sinknode_skreadings_snreadings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='snreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
