# Generated by Django 5.0.2 on 2024-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_skreadings_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinknode',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=119.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinknode',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=119.0, max_digits=9),
            preserve_default=False,
        ),
    ]
