# Generated by Django 5.1.1 on 2024-09-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sinknode_latitude_sinknode_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skreadings',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='SMSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('soil_moisture', models.DecimalField(decimal_places=7, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Sensor_Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensornode')),
            ],
        ),
        migrations.DeleteModel(
            name='SNReadings',
        ),
    ]
