# Generated by Django 5.1.1 on 2024-09-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_skreadings_bytes_received_skreadings_bytes_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinknode',
            name='area_address',
        ),
    ]
