# Generated by Django 5.1.1 on 2024-09-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_sinknode_area_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skreadings',
            name='bytes_received',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='bytes_sent',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='connected_clients',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='messages_received',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='messages_sent',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='sub_count',
        ),
        migrations.RemoveField(
            model_name='skreadings',
            name='total_clients',
        ),
    ]
