# Generated by Django 5.1.1 on 2024-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_skreadings_bytes_received_skreadings_bytes_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skreadings',
            name='bytes_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='bytes_sent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='connected_clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='messages_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='messages_sent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='sub_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skreadings',
            name='total_clients',
            field=models.IntegerField(),
        ),
    ]
