# Generated by Django 5.0.2 on 2024-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_skreadings_bytes_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
