# Generated by Django 5.0.2 on 2024-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_notifications_alter_skreadings_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
