# Generated by Django 5.0.2 on 2024-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_smsensorreadings_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
