# Generated by Django 5.0.2 on 2024-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_smsensorreadings_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
