# Generated by Django 5.0.2 on 2024-10-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_smsensorreadings_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorNodeAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField()),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensornode')),
            ],
        ),
        migrations.CreateModel(
            name='SinkNodeAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sinknode')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
