# Generated by Django 5.0.2 on 2024-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_snid_sensornode_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsensorreadings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
