# Generated by Django 5.0.2 on 2024-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_sensornodealerts_readings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorNodeAlerts',
            new_name='SMSensorAlerts',
        ),
    ]
