# Generated by Django 5.0.2 on 2024-11-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_sensornodealerts_smsensoralerts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsensoralerts',
            old_name='readings',
            new_name='data',
        ),
    ]
