# Generated by Django 5.0.2 on 2024-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_sensornode_sink_node_alter_sinknode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornode',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
