# Generated by Django 5.0.2 on 2024-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sensornode_registered_sinknode_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornode',
            name='registered',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sinknode',
            name='registered',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
